const actionTypes = {
    LOGIN_REQUESTED: 'LOGIN_REQUESTED',
    LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT: 'LOGOUT',
    REGISTER_REQUESTED: 'REGISTER_REQUESTED',
    // REGISTER_SUCCESSFUL: 'REGISTER_SUCCESSFUL', -> Login successful
    REGISTER_FAILED: 'REGISTER_FAILED',
    INCREASE_REQUESTED: 'INCREASE_REQUESTED',
    INCREASE_SUCCESSFUL: 'INCREASE_SUCCESSFUL',
    INCREASE_FAILED: 'INCREASE_RFAILED',
    DECREASE_REQUESTED: 'DECREASE_REQUESTED',
    DECREASE_SUCCESSFUL: 'DECREASE_SUCCESSFUL',
    DECREASE_FAILED: 'DECREASE_FAILED'
};

export default actionTypes;
