const actionTypes = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    REGISTER: 'REGISTER',
    INCREMENT_WEEKLY: 'INCREMENT_WEEKLY',
    INCREMENT_MONTHLY: 'INCREMENT_MONTHLY',
    INCREMENT_YEARLY: 'INCREMENT_YEARLY',
    DECREMENT_WEEKLY: 'DECREMENT_WEEKLY',
    DECREMENT_MONTHLY: 'DECREMENT_MONTHLY',
    DECREMENT_YEARLY: 'DECREMENT_YEARLY'
};

export default actionTypes;
